In [1]:
from itertools import permutations
import numpy as np

def KT(sigma, pi):
  res = 0
  for i in range(len(pi) - 1):
    for j in range(i + 1, len(pi)):
      if sigma[i] < sigma[j] and pi[i] > pi[j] or sigma[i] > sigma[j] and pi[i] < pi[j]:
        res += 1
  return res

In [18]:
k = 5
perms = list(permutations(range(k)))
np.unique([KT(x, range(k)) for x in perms], return_counts=True)[1]

array([ 1,  4,  9, 15, 20, 22, 20, 15,  9,  4,  1], dtype=int64)

In [19]:
k = 4
perms = list(permutations(range(k)))
np.unique([KT(x, range(k)) for x in perms], return_counts=True)[1]

array([1, 3, 5, 6, 5, 3, 1], dtype=int64)

In [26]:
k = 6
perms = list(permutations(range(k)))
a = np.unique([KT(x, range(k)) for x in perms], return_counts=True)[1]
print(a, sep='')

[  1   5  14  29  49  71  90 101 101  90  71  49  29  14   5   1]
